[package]
name = "beanstalkd"
version = "0.3.3"
authors = ["Johannes Schickling <schickling.j@gmail.com>"]
license = "MIT OR Apache-2.0"
homepage = "https://github.com/schickling/rust-beanstalkd"
repository = "https://github.com/schickling/rust-beanstalkd"
description = "Easy-to-use beanstalkd client for Rust (IronMQ compatible)"
keywords = ["beanstalkd", "queue", "worker", "ironmq"]
readme = "README.md"

[lib]
name = "beanstalkd"
path = "src/lib.rs"

[dependencies]
bufstream = "*"
